[project]
name = "filecheck"
version = "1.0.6"
description = "A Python-native clone of LLVMs FileCheck tool"
authors = [{ name = "Anton Lydike", email = "me@antonlydike.de" }]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/AntonLydike/filecheck"
repository = "https://github.com/AntonLydike/filecheck"
keywords = ["tests", "filecheck", "llvm"]
requires-python = ">=3.10"

[project.scripts]
filecheck = "filecheck.main:main"

[dependency-groups]
dev = [
    "lit>=18.1.8",
    "pre-commit>=3.7.1",
    "pyright>=1.1.370",
    "pytest>=8.2.2",
    "ruff>=0.16.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["filecheck"]

[tool.ruff]
line-length = 88

[tool.pyright]
typeCheckingMode = "strict"
"include" = ["filecheck"]

[tool.pytest.ini_options]
python_files = ["tests/*test_*.py"]
python_classes = "Test_*"
python_functions = "test_*"
addopts = ["--durations=20", "--maxfail=5"]
