# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI - Python-based Testing

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4

    - name: Install package locally
      run: |
        set -xeu -o pipefail
        poetry env use $(which python${{ matrix.python-version }})
        poetry install
        poetry run python --version

    - name: Execute lit tests
      run: |
        poetry run lit -v tests/filecheck/

    - name: Execute pytest tests
      run: |
        poetry run pytest
