# This workflow check the format all files in the repository
# * It checks that all nonempty files have a newline at the end
# * It checks that there are no whitespaces at the end of lines
# * It checks that Python files are formatted with black

name: Code Formatting and Pyright

on:
  pull_request:
  push:
    branches: [main]

jobs:
  code-formatting:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run code formatting checks with pre-commit
      uses: pre-commit/action@v3.0.0

    - name: Install Dependencies
      run: |
        pip install poetry
        poetry install

    - name: Run Pyright
      run: |
        poetry run pyright
